class Note:
    def __init(self, ...):
        self._title = ...
        self._tags = ...
        self._note = ...
    def ...(self, ...):
        ...


def main():
    choice = input("what do you want to do")
    if choice == "write":
        ...
    elif choice == "search":
        ...
    else:
        ...


if __name__ == "__main__":
    main()
